"""add on delete cascade to account_id in expenses

Revision ID: e46dea4affd7
Revises: 24a0aea19423
Create Date: 2024-12-11 20:05:21.596554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46dea4affd7'
down_revision = '24a0aea19423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('expenses_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_constraint('incomes_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incomes_account_id_fkey', 'accounts', ['account_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('expenses_account_id_fkey', 'accounts', ['account_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
